### ISSUE TITLE
Usage with Vue3 

### ISSUE THREAD

**Issue by seyidaniels** [setaman/vue-ellipse-progress#103]
I can't get this to work with Vue 3 and typescript, I keep getting the error below

<img width="602" alt="Screenshot 2021-02-26 at 23 48 54" src="https://user-images.githubusercontent.com/19833704/109363573-33d12b00-788d-11eb-8b6e-315a24fad682.png">

**Comment by setaman** [comment]
@seyidaniels Hi,

note that only `v2.x` is compatible with Vue 3! If you are already using the right version, please provide detailed info on how you are initializing and using the component.

**Comment by dexcell** [comment]
I can confirm it works with vue3 

```
import { VeProgress } from 'vue-ellipse-progress'

export default {
  components: {
    VeProgress,
  },
  setup() {
  }
}
```

**Comment by starkana** [comment]
Why is this component still in beta?

**Comment by setaman** [comment]
@starkana 
All implementation work is done, v2 is well tested and just waiting to be released. I am trying hard to find some time to prepare for the release (migrate to GitHub actions, docs, demos etc.). Hopefully I will be able to release the stable version this week.
