### ISSUE TITLE
[Feature request] Allow specifying progress bar color with CSS classes

### ISSUE THREAD

**Issue by DamianGlowala** [setaman/vue-ellipse-progress#104]
I'm using TailwindCSS and for my use case I find it difficult to apply a color to the progress bar with a **different color whenever a user hovers over the button** in which the spinner is in.

Regardless of the use case above it would be great to reuse already declared color classes rather than providing their CSS or hex equivalents, which are hardcoded and not CSS framework-dependent.

**Comment by setaman** [comment]
@DamianGlowala Hi, thanks for your suggestion and sorry for the late reply. I understand your point. I saw that Tailwind also has classes for SVG, so you could use that to control the colors as well. On one hand this case is quite framework specific, on the other hand it would give more flexibility.

Your issue made me think about how to give more freedom to the users. The classes would definitely be an easy way to do that. However, there are a some points that, in my opinion, could limit the flexibility:
* I would have to add a prop like `progressClass` for all circles, progress, fill, empty... -> verbose props interface
* styles specificity, custom classes have to override internally applied styles
* scoped styles could be a problem in some case and the user have to wrap the component in another component to apply classes

The issue your described is definitely one thing I will like to see in my library. I already have some thoughts on it that I need to evaluate. If I find a satisfactory solution, it will be added in later v2.x version. You are welcome to think along and suggest a possible solution.
