### ISSUE TITLE
'document is not defined' when using with nuxt.js

### ISSUE THREAD

**Issue by alitnk** [setaman/vue-ellipse-progress#108]
I'm trying to use this with nuxt.js
I made a plugin file with the following content:
```
import Vue from 'vue'
import VueEllipseProgress from 'vue-ellipse-progress'

Vue.use(VueEllipseProgress)
```
and get the `document is not defined` error.
I've tried putting it in <client-only> tag but still getting the same error.
Any fix?

**Comment by setaman** [comment]
@alitnk 

Confirmed. I tried to follow the official Nuxt guide for [plugins](https://nuxtjs.org/docs/2.x/configuration-glossary/configuration-plugins), But that did not work:
```js
//plugins/vue-ellipse-progress.js

import Vue from 'Vue';
import VueEllipseProgress from "vue-ellipse-progress";
Vue.use(VueEllipseProgress);
```

```js
//nuxt.config.js

plugins: [
    {
      src: '@/plugins/vue-ellipse-progress.js',
      mode: 'client'
    },
  ],
```
```vue
<client-only>
     <vue-ellipse-progress :progress="50" />
 </client-only>
```
Although the error disappears, another error `Unknown custom element: <vue-ellipse-progress>` appears instead. I am not a Nuxt expert and have tried all possible options found, but without success.The error has only to do with Vue Build and Nuxt, not with the source code. I need to invest more time in this.

**Comment by setaman** [comment]
So, the plugin initialization in my first comment is correct and it works! I just realized that i imported `Vue` instead of `vue` 😐. That was just a little typo that had made me crazy.

**Comment by matamune94** [comment]
You can call plugin in mouted.
Template
```
<template>
      <component
        :is="vueEllipseProgress"
        v-if="vueEllipseProgress"
        :progress="progress"
      />
</template>
```

Script
```
  data() {
    return {
      vueEllipseProgress: null
    }
  },
  mounted() {
    const { VueEllipseProgress } = require('vue-ellipse-progress')
    // console.log(vueEllipseProgress)
    this.vueEllipseProgress = VueEllipseProgress
    // console.log(VueEllipseProgress.default)
  },
```

**Comment by Timon0305** [comment]
so how can we fix this issue?

**Comment by setaman** [comment]
@Timon0305 just by following the Nuxt 2/Nuxt 3 official guides for plugins. Maybe the info in the [new yet unreleased docs](https://setaman.github.io/vue-ellipse-progress-docs/guide/installation.html#ssr) can also be useful.

**Comment by Timon0305** [comment]
> @Timon0305 just by following the Nuxt 2/Nuxt 3 official guides for plugins. Maybe the info in the [new yet unreleased docs](https://setaman.github.io/vue-ellipse-progress-docs/guide/installation.html#ssr) can also be useful.

Could you please tell me more ?

**Comment by setaman** [comment]
what is your setup? What exactly is not forking for you from the linked guides and what are the errors?

**Comment by Timon0305** [comment]
![Screenshot 2023-01-12 at 21 31 33](https://user-images.githubusercontent.com/59460476/212163206-a12332e4-4c43-4607-835e-1e82eeb50d64.png)
When I start project, it says there is no issue. 
But as you can see, project is not runinig
<img width="2443" alt="Screenshot 2023-01-12 at 21 32 27" src="https://user-images.githubusercontent.com/59460476/212163362-07874f44-1aee-43f4-b774-6cc7a462982b.png">

**Comment by setaman** [comment]
i don't see any evidence that the error is related to this plugin. You have to investigate the error more deeply and find detailed error logs.

**Comment by Timon0305** [comment]
project said there is no issue.

**Comment by setaman** [comment]
i can't help you debugging your project. If you have some concrete issue with the plugin, please open new issue and describe your problem detailed as possible. This issue was already resolved

**Comment by Timon0305** [comment]
> 

if resolved, where can I find?

**Comment by setaman** [comment]
right [here](https://github.com/setaman/vue-ellipse-progress/issues/108#issuecomment-808607720)

**Comment by Timon0305** [comment]
![Screenshot 2023-01-12 at 22 20 40](https://user-images.githubusercontent.com/59460476/212172289-14991659-907f-4d49-b784-64d904f8a687.png)
I tried to import that module but I got new issue

**Comment by setaman** [comment]
Did you added the plugin as Nuxt plugin following the official Nuxt documentation?

**Comment by Timon0305** [comment]
yes

**Comment by setaman** [comment]
Could you please share your project or at least all relevant code parts?

**Comment by Timon0305** [comment]
this project is private
