### ISSUE TITLE
empty progress

### ISSUE THREAD

**Issue by nbhkph** [setaman/vue-ellipse-progress#113]
I would like the circle progress to be completely empty when set progress to 0, how would i do that? since there is a little dot of progress when 0 progress.

**Comment by setaman** [comment]
Hi @nbhkph 

I left a small dot there at 0 Progress because that is actually a value as well. That was the design decision I made at those times. Maybe it wasn't the best decision.
Anyway you can fix this with [`noData`](https://github.com/setaman/vue-ellipse-progress#nodata) state prop like follows:
```vue
<vue-ellipse-progress :propgress="progress" :no-data="progress === 0" />
```
The progress line will disappear. If it helps, feel free to close the Issue, otherwise let as discuss a better solution.

**Comment by nbhkph** [comment]
Thanks for answering!

it works, but when data is set to false it hides the whole design any solution for that?

**Comment by setaman** [comment]
@nbhkph 

Yes, this is the obvious downside of the proposed solution. I'm already thinking about how to make the component behavior more flexible in different states, but that's a question for future releases.

Let me explain you, why i left this small dot for 0 progress. During the development i have created many different plain circles, e.g. with transparent empty lines. And with 0 progress simply none of the lines would be displayed. I found this irritating and left this point there to indicate the presence of the circle. So, this is more the question on the philosophy, not how to fix this.

But, i have another dirty workaround for you. You could change the line type depending on the progress like this: `:line="progress === 0 ? 'butt' : 'round'"`. This would hide the progress line and does not brake any styles, but have downsides too. 

Also you could change the styles property `stroke-dashoffset` of the `circle.ep-circle-progress` element manually. You just need to add `0.5` to the current value to hide the line completely. But yeah, could be a little bit tricky.

It's anything i can suggest you for now, without touching the code base. Let me know, if you have further questions or need help!

**Comment by nbhkph** [comment]
Okay thanks for the explanation!
