### ISSUE TITLE
this project cant be used with typescript

### ISSUE THREAD

**Issue by dannydulai** [setaman/vue-ellipse-progress#133]
It needs a index.d.ts file

**Comment by setaman** [comment]
@dannydulai 

Hi, the projects is written in plain JS, there can't be any `*.d.ts` files. I don't have much experience with TS, but I'm pretty sure that the component can be used in any TypeScript Vue project. 

If you need further help, feel free to write here what kind of difficulties you have with TypeScript. Maybe someone will pass around here who can help you.

**Comment by dannydulai** [comment]
For anyone else who wants to use this, I got it working using the instructions here: 

https://www.detroitlabs.com/blog/2018/02/28/adding-custom-type-definitions-to-a-third-party-library/

I just added a src/types/vue-ellipse-progress/index.d.ts to my project that contains 1 line: ```declare module 'vue-ellipse-progress';```

It was fine for me as I don't use any methods or properties of this component, but it'll need to be done properly for anyone who does.
