### ISSUE TITLE
Gradient not applying correctly

### ISSUE THREAD

**Issue by geobotsar81** [setaman/vue-ellipse-progress#139]
Seems like the gradient is not applying correctly.
Instead of applying the 100% offset to the end of the circle(100%) it seems to be applied at 50% and then the colors repeat in inverse for the other half:

For example green is applied to 0% orange to 50% and red to 100%.
![image](https://user-images.githubusercontent.com/67507417/133033155-38461b84-2b9d-4529-b3d8-b8514a4e2619.png)

Below you can see that red is applied to the 50% and then the colors repeat from 50% to 100% in inverse

![image](https://user-images.githubusercontent.com/67507417/133033348-c6c9c1f0-feb2-4e25-abed-087e08bf7f41.png)

**Comment by setaman** [comment]
Hello @geobotsar81 

i think, what are you trying to achieve is the green-orange-red gradient to follow along with the progress line, this could be possibly with the conical gradient (see #107 ).

What you observe is a linear gradient from bottom to top and this is the currently available behavior of SVG gradients in modern browsers. It becomes more clear with thicker lines like in this [example](https://codesandbox.io/s/beautiful-resonance-47klj?file=/src/App.vue). So far I haven't found a simple and elegant way to implement canonical gradients. I am open for any suggestions.

If you want to communicate the progress visually with colors. the work around could be just to change the progress line color depending on the `progress` value.

**Comment by geobotsar81** [comment]
Thanks, that makes sense, wasnt aware of these limitations. Thanks for the suggestion, will give it a go!
