### ISSUE TITLE
ssr aware

### ISSUE THREAD

**Issue by cezarneaga** [setaman/vue-ellipse-progress#143]
this is related to v2.0.0

Hi Sergej,

love what you did with this package. so before all, thank you for sharing it with us.

i am using this plugin with vitesse and ssg/ssr. i had to use a dynamic import behind a `isClient` condition because otherwise the ssr build breaks with `document is not defined`.

couldn't find in this branch exactly where in code this happens. could you help me out finding it so that maybe i can submit a PR to make it work without this.

thanks,
Cezar

**Comment by setaman** [comment]
@cezarneaga Hello Cezar,

i'm glad you find the plugin useful. 

I guess you were looking for the usage of `document` in the code. I'm not using any DOM API's explicitly. But i'm relying on the CSS computed properties (e.g.  [here](https://github.com/setaman/vue-ellipse-progress/blob/dev/src/components/Circle/circleMixin.js#L237)) to create all the fancy animation stuff and i'm pretty sure  Vue internals use `document` somewhere in the deep to update the variables.

We had already an `document is not defined` issue #108. So yeah, for the SSR build it's currently required to include the plugin only in browser environment. I'm actually not a SSR expert and would much appreciate any help. If you have an idea on how to make the lives easier for the people who build SSR apps, feel free to submit a PR, or just discuss it here.

**Comment by cezarneaga** [comment]
not sure those are the cause. baybe some usage of innerHeight?

**Comment by setaman** [comment]
no, i I had thought about `requestAnimationFrame`, but it actually produces an explicit error in non browser env.
