### ISSUE TITLE
when I use it in iphone6s with ios9，it Abnormal display

### ISSUE THREAD

**Issue by MonsterGoGoGo** [setaman/vue-ellipse-progress#144]
![image](https://user-images.githubusercontent.com/39951035/143802305-7e9b5f0c-729f-435f-85e2-cbe6709d3c61.png)
it should be 
![image](https://user-images.githubusercontent.com/39951035/143802339-b4679687-982a-4342-ad2d-6c9dd46c5ef0.png)

**Comment by setaman** [comment]
@MonsterGoGoGo 

Hello, thanks for the report. Can you also tell me what browser and what plugin version you are using and share please you circle configuration (code). 

The library targets modern browsers, there are chances that your browser is just to old. But i need to further investigate it.

**Comment by MonsterGoGoGo** [comment]
> 

I used the plugin version is ^1.3.0，it was used in our own app，a h5 page in the app's webview,  so I think it's the ios9 system inner broswer,  I have fixed this issue by add some styles, I think  because of the flex style is not Incompatible with older browsers
`.ep-content {
    position: relative;
    .ep-svg-container {
        display: flex;
        position: relative;
    }
    .ep-legend--container {
        display: flex;
        align-items: center;
        justify-content: center;
        left: 0;
        right: 0;
        top: 0;
        bottom: 0;
    }
}`

**Comment by setaman** [comment]
@MonsterGoGoGo 

ok, thanks for letting me know. I will take a look at the styles at the end of the year. Maybe i can better support old browsers.
