### ISSUE TITLE
I guess I cant installed it tell me why and pls help me fixing

### ISSUE THREAD

**Issue by Keremunce** [setaman/vue-ellipse-progress#145]
![image](https://user-images.githubusercontent.com/84583296/144388096-65a1a87c-5b60-43c9-b362-93944e1d1bb4.png)
![image](https://user-images.githubusercontent.com/84583296/144388509-7dbe1690-6d74-4402-bd96-ef5dc5cda127.png)
I guess i cant installed it 
![image](https://user-images.githubusercontent.com/84583296/144388673-f93c85e7-8549-428a-834c-a55e56dea3f3.png)

**Comment by setaman** [comment]
@Keremunce  Hello,
could you please show me how you are initializing and using the plugin

**Comment by Keremunce** [comment]
> 

![image](https://user-images.githubusercontent.com/84583296/144392158-45a290b0-de3d-4d6e-9aec-54cf584a1daf.png)
if you mean app.vue I'm using node.js ````npm node serve``` otherwise i dont understand please help me

**Comment by setaman** [comment]
i mean where you are importing the plugin in your code, something like:
```js
import VueEllipseProgress from 'vue-ellipse-progress';
Vue.use(VueEllipseProgress);
```

**Comment by Keremunce** [comment]
![image](https://user-images.githubusercontent.com/84583296/144393094-cb90324a-a448-4c5d-af0b-fec18d3ae383.png)

**Comment by setaman** [comment]
please note, as documented [here](https://github.com/setaman/vue-ellipse-progress/tree/v2-dev#installation-options), you have to properly initialize the v2.0.0, you use the wrong naming:
```js
// install
npm i vue-ellipse-progress@next
// initialize
import veProgress from "vue-ellipse-progress";
createApp(App).use(veProgress); // use correct name !
// use
<ve-progress :progress="50"/>

```

**Comment by Keremunce** [comment]
> please note, as documented [here](https://github.com/setaman/vue-ellipse-progress/tree/v2-dev#installation-options), you have to properly initialize the v2.0.0, you use the wrong naming:
> 
> ```js
> // install
> npm i vue-ellipse-progress@next
> // initialize
> import veProgress from "vue-ellipse-progress";
> createApp(App).use(veProgress); // use correct name !
> // use
> <ve-progress :progress="50"/>
> ```



> please note, as documented [here](https://github.com/setaman/vue-ellipse-progress/tree/v2-dev#installation-options), you have to properly initialize the v2.0.0, you use the wrong naming:
> 
> ```js
> // install
> npm i vue-ellipse-progress@next
> // initialize
> import veProgress from "vue-ellipse-progress";
> createApp(App).use(veProgress); // use correct name !
> // use
> <ve-progress :progress="50"/>
> ```

Appreciated man thank you so much
