### ISSUE TITLE
Can i define `:progress = (value)`

### ISSUE THREAD

**Issue by Keremunce** [setaman/vue-ellipse-progress#146]
I need to be defined `:progress = (VALUE)` as data.  How can I please help me 

https://stackoverflow.com/questions/70200039/vuejs-binding-progress-circle-with-text-active-class

**Comment by setaman** [comment]
@Keremunce 
i don't really understand what you are trying to achieve. Do you want to show some text besides the progress, e.g. `75 some text`?

**Comment by Keremunce** [comment]
I need to `:progress: 75` when it comes to 75--> stop progress and there will be a pop-up. Pop-up has a button, and when the button is clicked progress must be like this  `:progress: from 75 to 100` can we do that?

It's not have to be a start/stop option it might be `methods` but I don't know how to get `:progress="Value"` as a variable

**Comment by setaman** [comment]
you can use any variable as  `progress` as you usually do with Vue, e.g. `:progress="someVariable"`
