### ISSUE TITLE
Create non-pluggin version of the library

### ISSUE THREAD

**Issue by pngcsgta** [setaman/vue-ellipse-progress#152]
I would like to have the possibilities to import the library as a component or registering the component. Usage example: 

As a component:
```
import VueEllipseProgress from "vue-elpispis"

Vue.extend({
   name: "OterComp",
    components : {
        VueEllipseProgress,
    },
})
```

Registering the component:

```
import VueEllipseProgress from "vue-elpispis"
Vue.component('elipsisComponent', VueEllipseProgress);
```

**Comment by setaman** [comment]
@pngcsgta Hi,

i assume you are using version 1.x. In version 2 it's already implemented. I'm currently considering to release a v2.x compatible with both Vue 2 and 3. So all features would be available for all users. But that would take some time to evaluate this decision.

On the other hand it would be a small change in [`plugin.js`](https://github.com/setaman/vue-ellipse-progress/blob/master/src/plugin.js). Maybe you might to submit a PR?

**Comment by pngcsgta** [comment]
PR here: #153
