### ISSUE TITLE
Usage with vue3 + composition API

### ISSUE THREAD

**Issue by dcp-dev** [setaman/vue-ellipse-progress#178]
I'm trying to use your component on my Vue3 app with composition API and I'm not able to make it work even with the minimal setup.

I've got this very simple component and stuck with the following error `Uncaught (in promise) TypeError: t3.component is not a function`
```
<script setup>
import VueEllipseProgress from 'vue-ellipse-progress'
</script>

<template>
    <VueEllipseProgress :progress="90"/>
</template>
```

What am I doing wrong ?

**Comment by setaman** [comment]
@dcp-dev Helllo,

please make sure to refer to the documentation for [Vue 3 compatible version](https://github.com/setaman/vue-ellipse-progress/tree/v2-dev#import-component)

```js
// install
npm i vue-ellipse-progress@next
// import
import { VeProgress } from "vue-ellipse-progress";
// use
<ve-progress :progress="50"/>
```
