### ISSUE TITLE
Can't import on Vue 3

### ISSUE THREAD

**Issue by leogenot** [setaman/vue-ellipse-progress#197]
Using v2.1.1 I can't even do `import veProgress from "vue-ellipse-progress"` in my main.js, getting this error:
![Capture](https://user-images.githubusercontent.com/45610291/222532178-607068c3-b831-44ea-a233-42211713e32b.PNG)

This is my main.js:

![Capture2](https://user-images.githubusercontent.com/45610291/222532520-1458a6d5-b9ec-47cf-9ad5-f1342ba9b425.PNG)

without `import veProgress from "vue-ellipse-progress"` everything is fine

**Comment by setaman** [comment]
could you please provide minimal reproduction? Otherwise it's difficult to guess what's happening in your setup. I'm using this plugin 1-2 years in several Vue 3 projects without any issues.

**Comment by leogenot** [comment]
Ok I just created a new repo to isolate the bug but it seems that it was on my current repo so it is now working... I really don't know what happened here sorry

**Comment by setaman** [comment]
all fine, glad, anything is working!
