### ISSUE TITLE
confused on using slot property on vue3

### ISSUE THREAD

**Issue by soorajsprakash** [setaman/vue-ellipse-progress#200]
**Describe the bug**

In doc, its mentioned that we need to use slot like these: 
![image](https://user-images.githubusercontent.com/26853789/230316749-c708d760-eee2-4468-b2f5-623acaad7c67.png)

But in vue3, we cant do the same, it will throw error saying:
`error: slot attributes are deprecated     "vue/no-deprecated-slot-attribute"`

So, to stop error we need to use `v-slot:legend` or `#legend` right. So please update the docs.
Or could we use like this?

**To Reproduce**
1. Create empty component and try adding the slot property as mentioned in the doc

**Expected behavior**

**Screenshots**
Before:
![image](https://user-images.githubusercontent.com/26853789/230317823-a6549d4c-bb26-431d-adf1-5b3c5270fefa.png)

After (now no error): 
![image](https://user-images.githubusercontent.com/26853789/230317980-c6549cf3-ac0b-419c-89d0-6b03377b7abc.png)

**Desktop (it doesn't matter):**
 - OS:Ubuntu 22.10
 - Browser: Firefox & Chrome

**Plugin Version:** 2.1.1

**Comment by setaman** [comment]
You are right, thanks for pointing this out! But anyway, you should better take a look on the [slots section](https://github.com/setaman/vue-ellipse-progress/tree/v2-dev#slot-options) or even new [unreleased docs](https://setaman.github.io/vue-ellipse-progress-docs/guide/slots.html)

I will update readme to!

**Comment by soorajsprakash** [comment]
👍🏼 ok cool, will check it out.

**Comment by setaman** [comment]
fixed in [07e7c3b](https://github.com/setaman/vue-ellipse-progress/commit/07e7c3b52c853d464a1dbaddbe7be66843cccf22)
