### ISSUE TITLE
legendClass example

### ISSUE THREAD

**Issue by noqtuh** [setaman/vue-ellipse-progress#204]
Hi, maybe I'm stupid but I can't make the circle styling work with a custom CSS class in use of the legendClass tag. 
So is it possible to give a short example in the documents about how the legendClass tag works or did I misunderstood the function?

**Comment by setaman** [comment]
@noqtuh Hello, in general you just pass the class name as prop, take a look here: https://setaman.github.io/vue-ellipse-progress-docs/guide/options/legendClass.html

Then you can define the class somewhere in your app, e.g:

```css
.my-class {
  // my styles
}
```
Let me know if you have further questions.

**Comment by noqtuh** [comment]
thanks
