### ISSUE TITLE
Remove unused space for half circle

### ISSUE THREAD

**Issue by Miracutor** [setaman/vue-ellipse-progress#212]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Right now, even I specified `:half="true"`, the component will render at 200x200. When you specify half, it looks awkward to see that empty space in website layout.

**Additional context**
![image](https://github.com/setaman/vue-ellipse-progress/assets/46325590/18f73a10-d4c8-4bc9-8874-364fd7954a59)

**Comment by setaman** [comment]
Hey @Miracutor i can understand your point. There are also reasons why I leave the decision to the userland. For instance, take a look at the [example](https://setaman.github.io/vue-ellipse-progress-docs/guide/options/half.html#examples), the circle can be freely rotated, meaning we cannot just cut the  the height (or width) of the container. I would argue there is no universal default solution that will satisfy all use cases. But you can fix the layout on your own, e.g. with CSS:

```css
.ep-container,.ep-svg {
    height: 110px !important;
}
``` 

Let me know if that helps you!
