### ISSUE TITLE
:loader does not work in vue3

### ISSUE THREAD

**Issue by starkana** [setaman/vue-ellipse-progress#96]
Latest version of vue3 (3.0.0-5).

Try:

`<vue-ellipse-progress :loader="{ opacity: '0.6' }" />
`

![Screen Shot 2020-12-31 at 7 59 30 PM](https://user-images.githubusercontent.com/7329623/103432325-bd70bf00-4ba2-11eb-934c-437771529541.png)

**Comment by setaman** [comment]
@starkana yes, it is already fixed (ee378a7) and will be released soon in the first beta. For now just don't set `opacity`.
